<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    public function peoples () {
        return $this->hasMany(People::class);
    }

    public function delete()
    {
        $this->peoples()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
